sudo: required
dist: trusty
language: node_js
node_js:
- '9'
- '8'
- '7'
before_install:
- rm -rf node_modules
- npm install -g truffle
- npm install -g ganache-cli
install:
- npm install
before_script:
- cd $TRAVIS_BUILD_DIR
- chmod +x ./BranchPreScriptCheck.sh && ./BranchPreScriptCheck.sh
script:
- cd $TRAVIS_BUILD_DIR
- chmod +x ./BranchScript.sh && ./BranchScript.sh
deploy:
  matrix:
  - provider: s3
    bucket: dx-development
    secret_access_key:
      secure: W7stoKpbbLvmT0cLJbOUdK9t0IkTrTZYwlrVlyajLN86fnHvodpPhgwIoyYJVYzU9F+t4TdBUQVLAYXSf8mgXwK6COaHYjU8/HU/fNiIQLQQXxMUVg9beSSNMB+FLgIW0opDBK+fT15a9zKciLXWGHwKt7BZAbiuVQmT7KJ6g32wOKTqgVsTVuJyVNJUNTfNzEoTkEo0m7BbMybFFERwrh0ToOHaaFvI0PNhgPOVQCNFSVAa6/cRkWnlwRzoPsHxRYjy4/txR2GO3woakj8v+w8fDJAbWO+F7MEwzyfxwG4L1rh4Fz2Rwx93gfx7xQVYi2G/0axD0aC3XDngHzuiEP8ji/GuLi4ChFAM3lTnTTJnhmTxkvk/T7fM99ZQxjqD3FPUQHPqru/WCAVT6hMe4AOa1MzC3xk/fMkUH7RgfBWge/XpV+hYf5U8AkOHN25XHpzuRY71HouzE77dIMzLqZN1Jw5hgfMru233/34/defXev+Uu5K5OL5gNfM/dQEJ7pP2INifHmn0MzlLT5TUoGSxk5HaRBZMLje3YoLNfpMV9N4yDI37aUu6kCwNb0P/pP/9bqXZ8O+3/h4pDOwaa5C7t1sJMv+HzH6sjZCmKWfEE3eBsT8jrEaUN40GahN6+d+iWM8cxFohM6UV2aUH+a+wxqfyoGE+Jb7WJ/JYWxY=
    access_key_id:
      secure: jbHe4SAx3wR9OTysdyRZTLcAa9n07iZ2RnXsy5VcrjNxyRPK2k2/1dA5SHZmZwtuDG9ySyQdTGl0ecyZwSrFqu9J+Ubu3V33w8T06hW+orfn6WVolqVR5LchMlGu8wNyvpSHqJuGQolSthfLXb/ksGp6JqlGH4hjiObPhOgwsZhGreONVMHn/JjTVmNXVIINBDpOPgz9GNGGjYpY+6QX0I9hsr5VsytAbazizS/nyHoZyxCyxroEKpXDuzETkO6cr8Sj7dyB+OE9pe4ExBFFFrKWY9zkmwGRxOcF+uRkGJt90sTKbinHJL3DNZxxOu6C75LWoLKwdfmOku3l2tqSkyW1zTtzPgZmiKg4ACQteQsvJn4UvVJMY+c680txTS3AbCw6st9XpOiWB4YW2fnHrImFDNJkJ2WCkBydzmIEb5/vyRe5NpmCfEzqTaRgD/MCjYbg2+rQxxZSL0wLB7wEZXz+ootiaOmjIIZbbc6L3ZP2apV8j+zu0rz1hA5sXHuKV0t7YanuZpA0AgF47lFutm5znlFwDvOIRPwpBJIyYiZnlB0fEgmhJyHSlHklkuelAdywzf9jp9u3jIRRglGsS7ejeBPCldS8xOEdl+3Hh9U7A8f1PZKIr2p0TL+t9uwMuPWgldoqyX2wR6pnhJlpPpa9NrFmjlPUrnUgdCYaK54=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: development
  - provider: s3
    bucket: dx-staging
    secret_access_key:
      secure: W7stoKpbbLvmT0cLJbOUdK9t0IkTrTZYwlrVlyajLN86fnHvodpPhgwIoyYJVYzU9F+t4TdBUQVLAYXSf8mgXwK6COaHYjU8/HU/fNiIQLQQXxMUVg9beSSNMB+FLgIW0opDBK+fT15a9zKciLXWGHwKt7BZAbiuVQmT7KJ6g32wOKTqgVsTVuJyVNJUNTfNzEoTkEo0m7BbMybFFERwrh0ToOHaaFvI0PNhgPOVQCNFSVAa6/cRkWnlwRzoPsHxRYjy4/txR2GO3woakj8v+w8fDJAbWO+F7MEwzyfxwG4L1rh4Fz2Rwx93gfx7xQVYi2G/0axD0aC3XDngHzuiEP8ji/GuLi4ChFAM3lTnTTJnhmTxkvk/T7fM99ZQxjqD3FPUQHPqru/WCAVT6hMe4AOa1MzC3xk/fMkUH7RgfBWge/XpV+hYf5U8AkOHN25XHpzuRY71HouzE77dIMzLqZN1Jw5hgfMru233/34/defXev+Uu5K5OL5gNfM/dQEJ7pP2INifHmn0MzlLT5TUoGSxk5HaRBZMLje3YoLNfpMV9N4yDI37aUu6kCwNb0P/pP/9bqXZ8O+3/h4pDOwaa5C7t1sJMv+HzH6sjZCmKWfEE3eBsT8jrEaUN40GahN6+d+iWM8cxFohM6UV2aUH+a+wxqfyoGE+Jb7WJ/JYWxY=
    access_key_id:
      secure: jbHe4SAx3wR9OTysdyRZTLcAa9n07iZ2RnXsy5VcrjNxyRPK2k2/1dA5SHZmZwtuDG9ySyQdTGl0ecyZwSrFqu9J+Ubu3V33w8T06hW+orfn6WVolqVR5LchMlGu8wNyvpSHqJuGQolSthfLXb/ksGp6JqlGH4hjiObPhOgwsZhGreONVMHn/JjTVmNXVIINBDpOPgz9GNGGjYpY+6QX0I9hsr5VsytAbazizS/nyHoZyxCyxroEKpXDuzETkO6cr8Sj7dyB+OE9pe4ExBFFFrKWY9zkmwGRxOcF+uRkGJt90sTKbinHJL3DNZxxOu6C75LWoLKwdfmOku3l2tqSkyW1zTtzPgZmiKg4ACQteQsvJn4UvVJMY+c680txTS3AbCw6st9XpOiWB4YW2fnHrImFDNJkJ2WCkBydzmIEb5/vyRe5NpmCfEzqTaRgD/MCjYbg2+rQxxZSL0wLB7wEZXz+ootiaOmjIIZbbc6L3ZP2apV8j+zu0rz1hA5sXHuKV0t7YanuZpA0AgF47lFutm5znlFwDvOIRPwpBJIyYiZnlB0fEgmhJyHSlHklkuelAdywzf9jp9u3jIRRglGsS7ejeBPCldS8xOEdl+3Hh9U7A8f1PZKIr2p0TL+t9uwMuPWgldoqyX2wR6pnhJlpPpa9NrFmjlPUrnUgdCYaK54=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master
